CREATE TABLE USERS (
    id INT AUTO_INCREMENT PRIMARY KEY,
    email VARCHAR(255),
    name VARCHAR(255),
    password VARCHAR(255),
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT USERS_index UNIQUE (email)
);

CREATE TABLE RENTALS (
    id INT AUTO_INCREMENT PRIMARY KEY,
    name VARCHAR(255),
    surface DECIMAL(10),
    price DECIMAL(10),
    picture VARCHAR(255),
    description VARCHAR(2000),
    owner_id INT NOT NULL,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    FOREIGN KEY (owner_id) REFERENCES USERS(id)
);

CREATE TABLE MESSAGES (
    id INT AUTO_INCREMENT PRIMARY KEY,
    rental_id INT,
    user_id INT,
    message VARCHAR(2000),
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    FOREIGN KEY (user_id) REFERENCES USERS(id),
    FOREIGN KEY (rental_id) REFERENCES RENTALS(id)
);
